// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckoutBranch(arg1:string,arg2:string):Promise<string>;

export function FetchAllPrune(arg1:string):Promise<string>;

export function GetLocalBranches(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Log(arg1:string):Promise<string>;

export function Pull(arg1:string):Promise<string>;

export function ResetHead(arg1:string):Promise<string>;

export function Status(arg1:string):Promise<string>;

export function Suspend(arg1:string):Promise<string>;
