// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckoutBranch(arg1, arg2) {
  return window['go']['main']['App']['CheckoutBranch'](arg1, arg2);
}

export function FetchAllPrune(arg1) {
  return window['go']['main']['App']['FetchAllPrune'](arg1);
}

export function GetLocalBranches(arg1) {
  return window['go']['main']['App']['GetLocalBranches'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function Pull(arg1) {
  return window['go']['main']['App']['Pull'](arg1);
}

export function ResetHead(arg1) {
  return window['go']['main']['App']['ResetHead'](arg1);
}

export function Status(arg1) {
  return window['go']['main']['App']['Status'](arg1);
}

export function Suspend(arg1) {
  return window['go']['main']['App']['Suspend'](arg1);
}
